language: php
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - vendor
install:
  - 'composer install'
php:
  - '7.3'
  - '7.4'
  - '8.0'
script:
  - 'composer lint'
  - 'composer sniff-summary'
  - 'composer sniff-errors-only'
  - 'composer test'
