version: '3.3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx.crt:/var/ssl/nginx.crt
        - ./docker/nginx.key:/var/ssl/nginx.key
        - .:/var/www/html
    ports:
        - "80:80"
        - "443:443"
  # Uncomment this block and comment the next db block
  # to use MySQL instead of Postgres
  # db:
  #   image: mysql:latest
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: udoit
  #     MYSQL_USER: udoit
  #     MYSQL_PASSWORD: udoit
  #   ports:
  #     - "3306:3306"
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: udoit
      POSTGRES_PASSWORD: udoit
      POSTGRES_DB: udoit
  php:
    build:
      context: .
      dockerfile: docker/php71-fpm.Dockerfile
    volumes:
      - .:/var/www/html
volumes:
  web:
  dbdata: