version: "3.9"

services:
  #db:
  #  image: mysql:latest
  #  platform: linux/amd64
  #  volumes:
  #    - dbdata:/var/lib/mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: udoit3
  #    MYSQL_USER: udoit
  #    MYSQL_PASSWORD: udoit
  #  ports:
  #    - "3306:3306"
  db:
    image: postgres:13.4
    platform: linux/amd64
    volumes:
      - dbdata:/var/lib/pgsql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: udoit
      POSTGRES_DB: udoit3
    ports:
      - "5432:5432"
  web:
      image: nginx:latest
      ports:
          - "8000:80"
      volumes:
          - .:/var/www/html
          - ./build/nginx/local.conf:/etc/nginx/conf.d/default.conf
      links:
          - php
      env_file:
        - .env
        - .env.local
  php:
      build:
        context: ./build/nginx
        dockerfile: Dockerfile.php.pdo.pgsql
      volumes:
          - ./:/var/www/html
      env_file:
        - .env
        - .env.local
  composer:
      build:
        context: ./build/nginx
        dockerfile: Dockerfile.composer
      command: "composer install --no-dev --no-interaction --no-progress --optimize-autoloader"
      volumes:
          - ./:/app
      env_file:
        - .env
        - .env.local
  yarn:
      image: node:16
      volumes:
          - ./:/app
      env_file:
        - .env
        - .env.local
      command: >
        bash -c '
        cd /app &&
        yarn install && 
        yarn build'

volumes:
  web:
  dbdata:

