version: '3.3'

services:
  web:
    image: nginx:stable-alpine
    volumes:
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/domain.crt:/var/ssl/domain.crt
        - ./docker/domain.key:/var/ssl/domain.key
        - .:/var/www/html
    ports:
        - "80:80"
        - "443:443"
  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udoit
      MYSQL_USER: udoit
      MYSQL_PASSWORD: udoit
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: docker/php71-fpm.Dockerfile
    volumes:
      - .:/var/www/html
volumes:
  web:
  dbdata: