# Placeholder
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: udoit-ingress
  labels:  
    name: udoit 
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service: 
      name: udoit-cluster-ip-service
      port:
        number: 9000
