apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml --chart
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yml --chart
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - name: udoit
          ports:
          - containerPort: 9000
        # We should be able to add all of these from one place instead of calling these all out individually
          envFrom:
            - configMapRef:
                name: udoit-config
          image: ghcr.io/ucfopen/udoit:dev-v3-3-0
          resources: {}
      restartPolicy: Always
status: {}


