name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
    - name: Install dependencies
      uses: php-actions/composer@v5
      with:
        php_version: 7.4

    - name: Run linters
      run: composer lint

    - name: Run sniggs
      run: composer sniff-summary

    - name: Run tests
      run: composer test
